In [41]:
import numpy as np
import pandas as pd
import uproot
import matplotlib.pyplot as plt

In [11]:
%%bash
pwd

/home/mponchio

In [6]:
mother_path = "../../mnt/SingleTrackTrees/Data/alice_data_2023_LHC23f_535087_apass4_1300_Thinner/Output/Run535087"

In [15]:
%ls $mother_path

Chunk0950/  Chunk1020/  Chunk1050/  Chunk1120/  Chunk1150/  Chunk1220/
Chunk1000/  Chunk1030/  Chunk1100/  Chunk1130/  Chunk1200/  Chunk1300/
Chunk1010/  Chunk1040/  Chunk1110/  Chunk1140/  Chunk1210/

In [28]:
data_path = "../../mnt/SingleTrackTrees/Data/alice_data_2023_LHC23f_535087_apass4_1300_Thinner/Output/Run535087/Chunk1300"
%ls $data_path

001_006/  003/  007_010/  ao2d_filelist.txt  outK0s.root

In [22]:
sim_mother_path = "../../mnt/SingleTrackTrees/Simulation"
%ls $sim_mother_path

alice_sim_2024_LHC24h1_1_536237_AOD/

In [23]:
sim_path = "../../mnt/SingleTrackTrees/Simulation/alice_sim_2024_LHC24h1_1_536237_AOD"
%ls $sim_path

ls: cannot open directory '../../mnt/SingleTrackTrees/Simulation/alice_sim_2024_LHC24h1_1_536237_AOD': Permission denied

In [74]:
a = mother_path+"/Chunk1300"
%ls  $a

001_006/  003/  007_010/  ao2d_filelist.txt  outK0s.root

In [32]:
mother_path+"/Chunk0950"

'../../mnt/SingleTrackTrees/Data/alice_data_2023_LHC23f_535087_apass4_1300_Thinner/Output/Run535087/Chunk0950'

In [79]:
"""
Paths:
Chunk0950                    /Chunk0950/001_007/AO2Dtree.root
Chunk1000                    [ /Chunk1000/001_005/AO2Dtree.root, /Chunk1000/006_009/AO2Dtree.root ]
Chunk1010                    [ /Chunk1010/001_005/AO2Dtree.root, /Chunk1010/006_010/AO2Dtree.root ]
Chunk1020                    /Chunk1020/001_007/AO2Dtree.root
Chunk1030                    [ /Chunk1030/001_005/AO2Dtree.root, /Chunk1030/006_011/AO2Dtree.root ]
Chunk1040                    /Chunk1040/001_007/AO2Dtree.root
Chunk1050                    [ /Chunk1050/001_005/AO2Dtree.root, /Chunk1050/006_010/AO2Dtree.root ]
Chunk1100                    [ /Chunk1100/001_005/AO2Dtree.root, /Chunk1100/006_009/AO2Dtree.root ]
Chunk1110                    /Chunk1110/001_005/AO2Dtree.root
Chunk1120                    [ /Chunk1120/001_005/AO2Dtree.root, /Chunk1120/006_011/AO2Dtree.root ]
Chunk1130                    /Chunk1130/001_008/AO2Dtree.root
Chunk1140                    [ /Chunk1140/001_006/AO2Dtree.root, /Chunk1120/007_011/AO2Dtree.root ]
Chunk1150                    /Chunk1150/001_007/AO2Dtree.root
Chunk1200                    [ /Chunk1200/001_006/AO2Dtree.root, /Chunk1120/007_011/AO2Dtree.root ]
Chunk1210                    /Chunk1210/001_008/AO2Dtree.root
Chunk1220                    /Chunk1220/001_008/AO2Dtree.root
Chunk1300                    [ /Chunk1300/001_006/AO2Dtree.root, /Chunk1300/003/AO2Dtree.root, /Chunk1300/007_010/AO2Dtree.root ]
"""

'\nPaths:\nChunk0950                    /Chunk0950/001_007/AO2Dtree.root\nChunk1000                    [ /Chunk1000/001_005/AO2Dtree.root, /Chunk1000/006_009/AO2Dtree.root ]\nChunk1010                    [ /Chunk1010/001_005/AO2Dtree.root, /Chunk1010/006_010/AO2Dtree.root ]\nChunk1020                    /Chunk1020/001_007/AO2Dtree.root\nChunk1030                    [ /Chunk1030/001_005/AO2Dtree.root, /Chunk1030/006_011/AO2Dtree.root ]\nChunk1040                    /Chunk1040/001_007/AO2Dtree.root\nChunk1050                    [ /Chunk1050/001_005/AO2Dtree.root, /Chunk1050/006_010/AO2Dtree.root ]\nChunk1100                    [ /Chunk1100/001_005/AO2Dtree.root, /Chunk1100/006_009/AO2Dtree.root ]\nChunk1110                    /Chunk1110/001_005/AO2Dtree.root\nChunk1120                    [ /Chunk1120/001_005/AO2Dtree.root, /Chunk1120/006_011/AO2Dtree.root ]\nChunk1130                    /Chunk1130/001_008/AO2Dtree.root\nChunk1140                    [ /Chunk1140/001_006/AO2Dtree.root, /Chunk1120/007_011/AO2Dtree.root ]\nChunk1150                    /Chunk1150/001_007/AO2Dtree.root\nChunk1200                    [ /Chunk1200/001_006/AO2Dtree.root, /Chunk1120/007_011/AO2Dtree.root ]\nChunk1210                    /Chunk1210/001_008/AO2Dtree.root\nChunk1220                    /Chunk1220/001_008/AO2Dtree.root\nChunk1300                    [ /Chunk1300/001_006/AO2Dtree.root, /Chunk1300/003/AO2Dtree.root, /Chunk1300/007_010/AO2Dtree.root ]\n'

In [81]:
file_path = mother_path+"/Chunk0950/001_007/AO2Dtree.root"
file = uproot.open(file_path)
file.classnames()

{'DF_2298181510431936;1': 'TDirectory',
 'DF_2298181510431936/O2collision_001;1': 'TTree',
 'DF_2298181510431936/O2filtertrack;1': 'TTree',
 'DF_2298181510431936/O2filtertrackextr;1': 'TTree',
 'DF_2298181510502944;1': 'TDirectory',
 'DF_2298181510502944/O2collision_001;1': 'TTree',
 'DF_2298181510502944/O2filtertrack;1': 'TTree',
 'DF_2298181510502944/O2filtertrackextr;1': 'TTree',
 'DF_2298181510571872;1': 'TDirectory',
 'DF_2298181510571872/O2collision_001;1': 'TTree',
 'DF_2298181510571872/O2filtertrack;1': 'TTree',
 'DF_2298181510571872/O2filtertrackextr;1': 'TTree',
 'DF_2298181510572384;1': 'TDirectory',
 'DF_2298181510572384/O2collision_001;1': 'TTree',
 'DF_2298181510572384/O2filtertrack;1': 'TTree',
 'DF_2298181510572384/O2filtertrackextr;1': 'TTree',
 'DF_2298181510642880;1': 'TDirectory',
 'DF_2298181510642880/O2collision_001;1': 'TTree',
 'DF_2298181510642880/O2filtertrack;1': 'TTree',
 'DF_2298181510642880/O2filtertrackextr;1': 'TTree',
 'DF_2298181510718144;1': 'TDirectory',
 'DF_2298181510718144/O2collision_001;1': 'TTree',
 'DF_2298181510718144/O2filtertrack;1': 'TTree',
 'DF_2298181510718144/O2filtertrackextr;1': 'TTree',
 'DF_2298181510718592;1': 'TDirectory',
 'DF_2298181510718592/O2collision_001;1': 'TTree',
 'DF_2298181510718592/O2filtertrack;1': 'TTree',
 'DF_2298181510718592/O2filtertrackextr;1': 'TTree',
 'DF_2298181510782496;1': 'TDirectory',
 'DF_2298181510782496/O2collision_001;1': 'TTree',
 'DF_2298181510782496/O2filtertrack;1': 'TTree',
 'DF_2298181510782496/O2filtertrackextr;1': 'TTree',
 'DF_2298181510857920;1': 'TDirectory',
 'DF_2298181510857920/O2collision_001;1': 'TTree',
 'DF_2298181510857920/O2filtertrack;1': 'TTree',
 'DF_2298181510857920/O2filtertrackextr;1': 'TTree',
 'DF_2298181510858464;1': 'TDirectory',
 'DF_2298181510858464/O2collision_001;1': 'TTree',
 'DF_2298181510858464/O2filtertrack;1': 'TTree',
 'DF_2298181510858464/O2filtertrackextr;1': 'TTree',
 'DF_2298181510928864;1': 'TDirectory',
 'DF_2298181510928864/O2collision_001;1': 'TTree',
 'DF_2298181510928864/O2filtertrack;1': 'TTree',
 'DF_2298181510928864/O2filtertrackextr;1': 'TTree',
 'DF_2298181511004288;1': 'TDirectory',
 'DF_2298181511004288/O2collision_001;1': 'TTree',
 'DF_2298181511004288/O2filtertrack;1': 'TTree',
 'DF_2298181511004288/O2filtertrackextr;1': 'TTree',
 'DF_2298181511004640;1': 'TDirectory',
 'DF_2298181511004640/O2collision_001;1': 'TTree',
 'DF_2298181511004640/O2filtertrack;1': 'TTree',
 'DF_2298181511004640/O2filtertrackextr;1': 'TTree',
 'DF_2298181511075168;1': 'TDirectory',
 'DF_2298181511075168/O2collision_001;1': 'TTree',
 'DF_2298181511075168/O2filtertrack;1': 'TTree',
 'DF_2298181511075168/O2filtertrackextr;1': 'TTree',
 'DF_2298181511144064;1': 'TDirectory',
 'DF_2298181511144064/O2collision_001;1': 'TTree',
 'DF_2298181511144064/O2filtertrack;1': 'TTree',
 'DF_2298181511144064/O2filtertrackextr;1': 'TTree',
 'DF_2298181511144288;1': 'TDirectory',
 'DF_2298181511144288/O2collision_001;1': 'TTree',
 'DF_2298181511144288/O2filtertrack;1': 'TTree',
 'DF_2298181511144288/O2filtertrackextr;1': 'TTree',
 'DF_2298181511215040;1': 'TDirectory',
 'DF_2298181511215040/O2collision_001;1': 'TTree',
 'DF_2298181511215040/O2filtertrack;1': 'TTree',
 'DF_2298181511215040/O2filtertrackextr;1': 'TTree',
 'DF_2298181511290176;1': 'TDirectory',
 'DF_2298181511290176/O2collision_001;1': 'TTree',
 'DF_2298181511290176/O2filtertrack;1': 'TTree',
 'DF_2298181511290176/O2filtertrackextr;1': 'TTree',
 'DF_2298181511290592;1': 'TDirectory',
 'DF_2298181511290592/O2collision_001;1': 'TTree',
 'DF_2298181511290592/O2filtertrack;1': 'TTree',
 'DF_2298181511290592/O2filtertrackextr;1': 'TTree',
 'DF_2298181511361248;1': 'TDirectory',
 'DF_2298181511361248/O2collision_001;1': 'TTree',
 'DF_2298181511361248/O2filtertrack;1': 'TTree',
 'DF_2298181511361248/O2filtertrackextr;1': 'TTree',
 'DF_2298181511430432;1': 'TDirectory',
 'DF_2298181511430432/O2collision_001;1': 'TTree',
 'DF_2298181511430432/O2filtertrack;1': 'TTree',
 'DF_2298181511430432/O2filtertrackextr;1': 'TTree',
 'DF_2298181511436512;1': 'TDirectory',
 'DF_2298181511436512/O2collision_001;1': 'TTree',
 'DF_2298181511436512/O2filtertrack;1': 'TTree',
 'DF_2298181511436512/O2filtertrackextr;1': 'TTree',
 'DF_2298181511507584;1': 'TDirectory',
 'DF_2298181511507584/O2collision_001;1': 'TTree',
 'DF_2298181511507584/O2filtertrack;1': 'TTree',
 'DF_2298181511507584/O2filtertrackextr;1': 'TTree',
 'DF_2298181511570176;1': 'TDirectory',
 'DF_2298181511570176/O2collision_001;1': 'TTree',
 'DF_2298181511570176/O2filtertrack;1': 'TTree',
 'DF_2298181511570176/O2filtertrackextr;1': 'TTree',
 'DF_2298181511576192;1': 'TDirectory',
 'DF_2298181511576192/O2collision_001;1': 'TTree',
 'DF_2298181511576192/O2filtertrack;1': 'TTree',
 'DF_2298181511576192/O2filtertrackextr;1': 'TTree',
 'DF_2298181511647360;1': 'TDirectory',
 'DF_2298181511647360/O2collision_001;1': 'TTree',
 'DF_2298181511647360/O2filtertrack;1': 'TTree',
 'DF_2298181511647360/O2filtertrackextr;1': 'TTree',
 'DF_2298181511716096;1': 'TDirectory',
 'DF_2298181511716096/O2collision_001;1': 'TTree',
 'DF_2298181511716096/O2filtertrack;1': 'TTree',
 'DF_2298181511716096/O2filtertrackextr;1': 'TTree',
 'DF_2298181511716224;1': 'TDirectory',
 'DF_2298181511716224/O2collision_001;1': 'TTree',
 'DF_2298181511716224/O2filtertrack;1': 'TTree',
 'DF_2298181511716224/O2filtertrackextr;1': 'TTree',
 'DF_2298181511787040;1': 'TDirectory',
 'DF_2298181511787040/O2collision_001;1': 'TTree',
 'DF_2298181511787040/O2filtertrack;1': 'TTree',
 'DF_2298181511787040/O2filtertrackextr;1': 'TTree',
 'DF_2298181511855872;1': 'TDirectory',
 'DF_2298181511855872/O2collision_001;1': 'TTree',
 'DF_2298181511855872/O2filtertrack;1': 'TTree',
 'DF_2298181511855872/O2filtertrackextr;1': 'TTree',
 'DF_2298181511862336;1': 'TDirectory',
 'DF_2298181511862336/O2collision_001;1': 'TTree',
 'DF_2298181511862336/O2filtertrack;1': 'TTree',
 'DF_2298181511862336/O2filtertrackextr;1': 'TTree',
 'DF_2298181511933312;1': 'TDirectory',
 'DF_2298181511933312/O2collision_001;1': 'TTree',
 'DF_2298181511933312/O2filtertrack;1': 'TTree',
 'DF_2298181511933312/O2filtertrackextr;1': 'TTree',
 'DF_2298181511995680;1': 'TDirectory',
 'DF_2298181511995680/O2collision_001;1': 'TTree',
 'DF_2298181511995680/O2filtertrack;1': 'TTree',
 'DF_2298181511995680/O2filtertrackextr;1': 'TTree',
 'DF_2298181512008608;1': 'TDirectory',
 'DF_2298181512008608/O2collision_001;1': 'TTree',
 'DF_2298181512008608/O2filtertrack;1': 'TTree',
 'DF_2298181512008608/O2filtertrackextr;1': 'TTree',
 'DF_2298181512073088;1': 'TDirectory',
 'DF_2298181512073088/O2collision_001;1': 'TTree',
 'DF_2298181512073088/O2filtertrack;1': 'TTree',
 'DF_2298181512073088/O2filtertrackextr;1': 'TTree',
 'DF_2298181512141856;1': 'TDirectory',
 'DF_2298181512141856/O2collision_001;1': 'TTree',
 'DF_2298181512141856/O2filtertrack;1': 'TTree',
 'DF_2298181512141856/O2filtertrackextr;1': 'TTree',
 'DF_2298181512148384;1': 'TDirectory',
 'DF_2298181512148384/O2collision_001;1': 'TTree',
 'DF_2298181512148384/O2filtertrack;1': 'TTree',
 'DF_2298181512148384/O2filtertrackextr;1': 'TTree',
 'DF_2298181512219392;1': 'TDirectory',
 'DF_2298181512219392/O2collision_001;1': 'TTree',
 'DF_2298181512219392/O2filtertrack;1': 'TTree',
 'DF_2298181512219392/O2filtertrackextr;1': 'TTree',
 'DF_2298181512281408;1': 'TDirectory',
 'DF_2298181512281408/O2collision_001;1': 'TTree',
 'DF_2298181512281408/O2filtertrack;1': 'TTree',
 'DF_2298181512281408/O2filtertrackextr;1': 'TTree',
 'DF_2298181512294752;1': 'TDirectory',
 'DF_2298181512294752/O2collision_001;1': 'TTree',
 'DF_2298181512294752/O2filtertrack;1': 'TTree',
 'DF_2298181512294752/O2filtertrackextr;1': 'TTree',
 'DF_2298181512365824;1': 'TDirectory',
 'DF_2298181512365824/O2collision_001;1': 'TTree',
 'DF_2298181512365824/O2filtertrack;1': 'TTree',
 'DF_2298181512365824/O2filtertrackextr;1': 'TTree',
 'DF_2298181512421120;1': 'TDirectory',
 'DF_2298181512421120/O2collision_001;1': 'TTree',
 'DF_2298181512421120/O2filtertrack;1': 'TTree',
 'DF_2298181512421120/O2filtertrackextr;1': 'TTree',
 'DF_2298181512441088;1': 'TDirectory',
 'DF_2298181512441088/O2collision_001;1': 'TTree',
 'DF_2298181512441088/O2filtertrack;1': 'TTree',
 'DF_2298181512441088/O2filtertrackextr;1': 'TTree',
 'DF_2298181512512064;1': 'TDirectory',
 'DF_2298181512512064/O2collision_001;1': 'TTree',
 'DF_2298181512512064/O2filtertrack;1': 'TTree',
 'DF_2298181512512064/O2filtertrackextr;1': 'TTree',
 'DF_2298181512567328;1': 'TDirectory',
 'DF_2298181512567328/O2collision_001;1': 'TTree',
 'DF_2298181512567328/O2filtertrack;1': 'TTree',
 'DF_2298181512567328/O2filtertrackextr;1': 'TTree',
 'DF_2298181512587552;1': 'TDirectory',
 'DF_2298181512587552/O2collision_001;1': 'TTree',
 'DF_2298181512587552/O2filtertrack;1': 'TTree',
 'DF_2298181512587552/O2filtertrackextr;1': 'TTree',
 'DF_2298181512652032;1': 'TDirectory',
 'DF_2298181512652032/O2collision_001;1': 'TTree',
 'DF_2298181512652032/O2filtertrack;1': 'TTree',
 'DF_2298181512652032/O2filtertrackextr;1': 'TTree',
 'DF_2298181512706816;1': 'TDirectory',
 'DF_2298181512706816/O2collision_001;1': 'TTree',
 'DF_2298181512706816/O2filtertrack;1': 'TTree',
 'DF_2298181512706816/O2filtertrackextr;1': 'TTree',
 'DF_2298181512727552;1': 'TDirectory',
 'DF_2298181512727552/O2collision_001;1': 'TTree',
 'DF_2298181512727552/O2filtertrack;1': 'TTree',
 'DF_2298181512727552/O2filtertrackextr;1': 'TTree',
 'DF_2298181512798208;1': 'TDirectory',
 'DF_2298181512798208/O2collision_001;1': 'TTree',
 'DF_2298181512798208/O2filtertrack;1': 'TTree',
 'DF_2298181512798208/O2filtertrackextr;1': 'TTree',
 'DF_2298181512846688;1': 'TDirectory',
 'DF_2298181512846688/O2collision_001;1': 'TTree',
 'DF_2298181512846688/O2filtertrack;1': 'TTree',
 'DF_2298181512846688/O2filtertrackextr;1': 'TTree',
 'DF_2298181512873664;1': 'TDirectory',
 'DF_2298181512873664/O2collision_001;1': 'TTree',
 'DF_2298181512873664/O2filtertrack;1': 'TTree',
 'DF_2298181512873664/O2filtertrackextr;1': 'TTree',
 'DF_2298181512937984;1': 'TDirectory',
 'DF_2298181512937984/O2collision_001;1': 'TTree',
 'DF_2298181512937984/O2filtertrack;1': 'TTree',
 'DF_2298181512937984/O2filtertrackextr;1': 'TTree',
 'DF_2298181512992768;1': 'TDirectory',
 'DF_2298181512992768/O2collision_001;1': 'TTree',
 'DF_2298181512992768/O2filtertrack;1': 'TTree',
 'DF_2298181512992768/O2filtertrackextr;1': 'TTree',
 'DF_2298181513013536;1': 'TDirectory',
 'DF_2298181513013536/O2collision_001;1': 'TTree',
 'DF_2298181513013536/O2filtertrack;1': 'TTree',
 'DF_2298181513013536/O2filtertrackextr;1': 'TTree',
 'DF_2298181513084192;1': 'TDirectory',
 'DF_2298181513084192/O2collision_001;1': 'TTree',
 'DF_2298181513084192/O2filtertrack;1': 'TTree',
 'DF_2298181513084192/O2filtertrackextr;1': 'TTree',
 'DF_2298181513132640;1': 'TDirectory',
 'DF_2298181513132640/O2collision_001;1': 'TTree',
 'DF_2298181513132640/O2filtertrack;1': 'TTree',
 'DF_2298181513132640/O2filtertrackextr;1': 'TTree',
 'DF_2298181513159968;1': 'TDirectory',
 'DF_2298181513159968/O2collision_001;1': 'TTree',
 'DF_2298181513159968/O2filtertrack;1': 'TTree',
 'DF_2298181513159968/O2filtertrackextr;1': 'TTree',
 'DF_2298181513224032;1': 'TDirectory',
 'DF_2298181513224032/O2collision_001;1': 'TTree',
 'DF_2298181513224032/O2filtertrack;1': 'TTree',
 'DF_2298181513224032/O2filtertrackextr;1': 'TTree',
 'DF_2298181513278816;1': 'TDirectory',
 'DF_2298181513278816/O2collision_001;1': 'TTree',
 'DF_2298181513278816/O2filtertrack;1': 'TTree',
 'DF_2298181513278816/O2filtertrackextr;1': 'TTree',
 'DF_2298181513306112;1': 'TDirectory',
 'DF_2298181513306112/O2collision_001;1': 'TTree',
 'DF_2298181513306112/O2filtertrack;1': 'TTree',
 'DF_2298181513306112/O2filtertrackextr;1': 'TTree',
 'DF_2298181510433760;1': 'TDirectory',
 'DF_2298181510433760/O2collision_001;1': 'TTree',
 'DF_2298181510433760/O2filtertrack;1': 'TTree',
 'DF_2298181510433760/O2filtertrackextr;1': 'TTree',
 'DF_2298181510498080;1': 'TDirectory',
 'DF_2298181510498080/O2collision_001;1': 'TTree',
 'DF_2298181510498080/O2filtertrack;1': 'TTree',
 'DF_2298181510498080/O2filtertrackextr;1': 'TTree',
 'DF_2298181510573696;1': 'TDirectory',
 'DF_2298181510573696/O2collision_001;1': 'TTree',
 'DF_2298181510573696/O2filtertrack;1': 'TTree',
 'DF_2298181510573696/O2filtertrackextr;1': 'TTree',
 'DF_2298181510573888;1': 'TDirectory',
 'DF_2298181510573888/O2collision_001;1': 'TTree',
 'DF_2298181510573888/O2filtertrack;1': 'TTree',
 'DF_2298181510573888/O2filtertrackextr;1': 'TTree',
 'DF_2298181510630912;1': 'TDirectory',
 'DF_2298181510630912/O2collision_001;1': 'TTree',
 'DF_2298181510630912/O2filtertrack;1': 'TTree',
 'DF_2298181510630912/O2filtertrackextr;1': 'TTree',
 'DF_2298181510706784;1': 'TDirectory',
 'DF_2298181510706784/O2collision_001;1': 'TTree',
 'DF_2298181510706784/O2filtertrack;1': 'TTree',
 'DF_2298181510706784/O2filtertrackextr;1': 'TTree',
 'DF_2298181510720064;1': 'TDirectory',
 'DF_2298181510720064/O2collision_001;1': 'TTree',
 'DF_2298181510720064/O2filtertrack;1': 'TTree',
 'DF_2298181510720064/O2filtertrackextr;1': 'TTree',
 'DF_2298181510770240;1': 'TDirectory',
 'DF_2298181510770240/O2collision_001;1': 'TTree',
 'DF_2298181510770240/O2filtertrack;1': 'TTree',
 'DF_2298181510770240/O2filtertrackextr;1': 'TTree',
 'DF_2298181510839552;1': 'TDirectory',
 'DF_2298181510839552/O2collision_001;1': 'TTree',
 'DF_2298181510839552/O2filtertrack;1': 'TTree',
 'DF_2298181510839552/O2filtertrackextr;1': 'TTree',
 'DF_2298181510866336;1': 'TDirectory',
 'DF_2298181510866336/O2collision_001;1': 'TTree',
 'DF_2298181510866336/O2filtertrack;1': 'TTree',
 'DF_2298181510866336/O2filtertrackextr;1': 'TTree',
 'DF_2298181510902816;1': 'TDirectory',
 'DF_2298181510902816/O2collision_001;1': 'TTree',
 'DF_2298181510902816/O2filtertrack;1': 'TTree',
 'DF_2298181510902816/O2filtertrackextr;1': 'TTree',
 'DF_2298181510978784;1': 'TDirectory',
 'DF_2298181510978784/O2collision_001;1': 'TTree',
 'DF_2298181510978784/O2filtertrack;1': 'TTree',
 'DF_2298181510978784/O2filtertrackextr;1': 'TTree',
 'DF_2298181511005984;1': 'TDirectory',
 'DF_2298181511005984/O2collision_001;1': 'TTree',
 'DF_2298181511005984/O2filtertrack;1': 'TTree',
 'DF_2298181511005984/O2filtertrackextr;1': 'TTree',
 'DF_2298181511042016;1': 'TDirectory',
 'DF_2298181511042016/O2collision_001;1': 'TTree',
 'DF_2298181511042016/O2filtertrack;1': 'TTree',
 'DF_2298181511042016/O2filtertrackextr;1': 'TTree',
 'DF_2298181511118176;1': 'TDirectory',
 'DF_2298181511118176/O2collision_001;1': 'TTree',
 'DF_2298181511118176/O2filtertrack;1': 'TTree',
 'DF_2298181511118176/O2filtertrackextr;1': 'TTree',
 'DF_2298181511145504;1': 'TDirectory',
 'DF_2298181511145504/O2collision_001;1': 'TTree',
 'DF_2298181511145504/O2filtertrack;1': 'TTree',
 'DF_2298181511145504/O2filtertrackextr;1': 'TTree',
 'DF_2298181511174944;1': 'TDirectory',
 'DF_2298181511174944/O2collision_001;1': 'TTree',
 'DF_2298181511174944/O2filtertrack;1': 'TTree',
 'DF_2298181511174944/O2filtertrackextr;1': 'TTree',
 'DF_2298181511250976;1': 'TDirectory',
 'DF_2298181511250976/O2collision_001;1': 'TTree',
 'DF_2298181511250976/O2filtertrack;1': 'TTree',
 'DF_2298181511250976/O2filtertrackextr;1': 'TTree',
 'DF_2298181511285376;1': 'TDirectory',
 'DF_2298181511285376/O2collision_001;1': 'TTree',
 'DF_2298181511285376/O2filtertrack;1': 'TTree',
 'DF_2298181511285376/O2filtertrackextr;1': 'TTree',
 'DF_2298181511314176;1': 'TDirectory',
 'DF_2298181511314176/O2collision_001;1': 'TTree',
 'DF_2298181511314176/O2filtertrack;1': 'TTree',
 'DF_2298181511314176/O2filtertrackextr;1': 'TTree',
 'DF_2298181511390208;1': 'TDirectory',
 'DF_2298181511390208/O2collision_001;1': 'TTree',
 'DF_2298181511390208/O2filtertrack;1': 'TTree',
 'DF_2298181511390208/O2filtertrackextr;1': 'TTree',
 'DF_2298181511431648;1': 'TDirectory',
 'DF_2298181511431648/O2collision_001;1': 'TTree',
 'DF_2298181511431648/O2filtertrack;1': 'TTree',
 'DF_2298181511431648/O2filtertrackextr;1': 'TTree',
 'DF_2298181511447136;1': 'TDirectory',
 'DF_2298181511447136/O2collision_001;1': 'TTree',
 'DF_2298181511447136/O2filtertrack;1': 'TTree',
 'DF_2298181511447136/O2filtertrackextr;1': 'TTree',
 'DF_2298181511523168;1': 'TDirectory',
 'DF_2298181511523168/O2collision_001;1': 'TTree',
 'DF_2298181511523168/O2filtertrack;1': 'TTree',
 'DF_2298181511523168/O2filtertrackextr;1': 'TTree',
 'DF_2298181511571424;1': 'TDirectory',
 'DF_2298181511571424/O2collision_001;1': 'TTree',
 'DF_2298181511571424/O2filtertrack;1': 'TTree',
 'DF_2298181511571424/O2filtertrackextr;1': 'TTree',
 'DF_2298181511586176;1': 'TDirectory',
 'DF_2298181511586176/O2collision_001;1': 'TTree',
 'DF_2298181511586176/O2filtertrack;1': 'TTree',
 'DF_2298181511586176/O2filtertrackextr;1': 'TTree',
 'DF_2298181511662368;1': 'TDirectory',
 'DF_2298181511662368/O2collision_001;1': 'TTree',
 'DF_2298181511662368/O2filtertrack;1': 'TTree',
 'DF_2298181511662368/O2filtertrackextr;1': 'TTree',
 'DF_2298181511717504;1': 'TDirectory',
 'DF_2298181511717504/O2collision_001;1': 'TTree',
 'DF_2298181511717504/O2filtertrack;1': 'TTree',
 'DF_2298181511717504/O2filtertrackextr;1': 'TTree',
 'DF_2298181511719104;1': 'TDirectory',
 'DF_2298181511719104/O2collision_001;1': 'TTree',
 'DF_2298181511719104/O2filtertrack;1': 'TTree',
 'DF_2298181511719104/O2filtertrackextr;1': 'TTree',
 'DF_2298181511801984;1': 'TDirectory',
 'DF_2298181511801984/O2collision_001;1': 'TTree',
 'DF_2298181511801984/O2filtertrack;1': 'TTree',
 'DF_2298181511801984/O2filtertrackextr;1': 'TTree',
 'DF_2298181511851680;1': 'TDirectory',
 'DF_2298181511851680/O2collision_001;1': 'TTree',
 'DF_2298181511851680/O2filtertrack;1': 'TTree',
 'DF_2298181511851680/O2filtertrackextr;1': 'TTree',
 'DF_2298181511857344;1': 'TDirectory',
 'DF_2298181511857344/O2collision_001;1': 'TTree',
 'DF_2298181511857344/O2filtertrack;1': 'TTree',
 'DF_2298181511857344/O2filtertrackextr;1': 'TTree',
 'DF_2298181511941312;1': 'TDirectory',
 'DF_2298181511941312/O2collision_001;1': 'TTree',
 'DF_2298181511941312/O2filtertrack;1': 'TTree',
 'DF_2298181511941312/O2filtertrackextr;1': 'TTree',
 'DF_2298181511990784;1': 'TDirectory',
 'DF_2298181511990784/O2collision_001;1': 'TTree',
 'DF_2298181511990784/O2filtertrack;1': 'TTree',
 'DF_2298181511990784/O2filtertrackextr;1': 'TTree',
 'DF_2298181512003840;1': 'TDirectory',
 'DF_2298181512003840/O2collision_001;1': 'TTree',
 'DF_2298181512003840/O2filtertrack;1': 'TTree',
 'DF_2298181512003840/O2filtertrackextr;1': 'TTree',
 'DF_2298181512074336;1': 'TDirectory',
 'DF_2298181512074336/O2collision_001;1': 'TTree',
 'DF_2298181512074336/O2filtertrack;1': 'TTree',
 'DF_2298181512074336/O2filtertrackextr;1': 'TTree',
 'DF_2298181512123680;1': 'TDirectory',
 'DF_2298181512123680/O2collision_001;1': 'TTree',
 'DF_2298181512123680/O2filtertrack;1': 'TTree',
 'DF_2298181512123680/O2filtertrackextr;1': 'TTree',
 'DF_2298181512150240;1': 'TDirectory',
 'DF_2298181512150240/O2collision_001;1': 'TTree',
 'DF_2298181512150240/O2filtertrack;1': 'TTree',
 'DF_2298181512150240/O2filtertrackextr;1': 'TTree',
 'DF_2298181512213472;1': 'TDirectory',
 'DF_2298181512213472/O2collision_001;1': 'TTree',
 'DF_2298181512213472/O2filtertrack;1': 'TTree',
 'DF_2298181512213472/O2filtertrackextr;1': 'TTree',
 'DF_2298181512262944;1': 'TDirectory',
 'DF_2298181512262944/O2collision_001;1': 'TTree',
 'DF_2298181512262944/O2filtertrack;1': 'TTree',
 'DF_2298181512262944/O2filtertrackextr;1': 'TTree',
 'DF_2298181512296672;1': 'TDirectory',
 'DF_2298181512296672/O2collision_001;1': 'TTree',
 'DF_2298181512296672/O2filtertrack;1': 'TTree',
 'DF_2298181512296672/O2filtertrackextr;1': 'TTree',
 'DF_2298181512346368;1': 'TDirectory',
 'DF_2298181512346368/O2collision_001;1': 'TTree',
 'DF_2298181512346368/O2filtertrack;1': 'TTree',
 'DF_2298181512346368/O2filtertrackextr;1': 'TTree',
 'DF_2298181512402272;1': 'TDirectory',
 'DF_2298181512402272/O2collision_001;1': 'TTree',

In [110]:
example = "DF_2298181510431936"
collision_ID = "O2collision_001"
track_ID = "O2filtertrack"
extra_ID = "O2filtertrackextr"

collision = file["/".join([example,collision_ID])].arrays(library="pd")
collision

,fIndexBCs,fPosX,fPosY,fPosZ,fCovXX,fCovXY,fCovYY,fCovXZ,fCovYZ,fCovZZ,fFlags,fChi2,fNumContrib,fCollisionTime,fCollisionTimeRes
0,2,-0.033514,-0.024783,0.354504,7.413328e-07,3.690366e-08,1.109205e-06,7.843482e-09,1.279404e-07,9.466894e-07,0,73.812500,35,-1.748899,6.085938
1,7,-0.038754,-0.028770,2.641132,4.872680e-06,-9.946525e-07,6.675720e-06,1.274981e-06,-3.534369e-07,6.373972e-06,0,32.218750,9,-2.496639,132.125000
2,8,-0.039419,-0.028016,3.692455,7.618219e-07,8.713687e-08,9.573996e-07,-1.129811e-07,2.110028e-09,8.097850e-07,0,64.937500,44,-5.133743,4.699219
3,12,-0.036251,-0.028028,6.088623,7.674098e-06,1.427718e-06,7.010996e-06,-1.431443e-06,-1.213513e-06,7.271767e-06,0,9.023438,7,-0.212461,10.125000
4,15,-0.038985,-0.025101,-3.147106,3.118068e-06,4.372559e-07,1.822598e-06,1.572073e-06,3.739260e-07,3.088266e-06,0,29.187500,21,3.790230,94.687500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12542,63764,-0.042396,-0.027650,0.589890,1.077354e-05,-1.979992e-06,1.402944e-05,2.734363e-06,-7.238239e-06,2.551079e-05,0,4.140625,4,-4.095558,10.015625
12543,63769,-0.031396,-0.021696,-1.898705,1.199543e-05,-1.845881e-06,6.385148e-06,8.954667e-07,-8.968636e-07,9.655952e-06,0,1.301758,2,0.191074,10.218750
12544,63772,-0.031406,-0.025635,-0.066785,7.487833e-06,5.597249e-07,4.637986e-06,-2.080575e-06,-1.402572e-06,7.763505e-06,0,7.378906,7,-0.979108,10.054688
12545,63775,-0.035513,-0.033282,5.457474,5.740672e-06,6.593764e-07,3.723428e-06,3.559515e-06,-5.261973e-07,8.836389e-06,0,9.000000,6,0.108864,1426.000000
12546,63783,-0.035849,-0.028874,-2.275398,5.371869e-06,-8.745119e-07,5.517155e-06,-2.814457e-06,4.205853e-06,1.537800e-05,0,5.234375,8,0.004323,1426.000000

In [111]:
track = file["/".join([example,track_ID])].arrays(library="pd")
track

,fIndexCollisions,fIsInsideBeamPipe,fTrackType,fX,fAlpha,fY,fZ,fSnp,fTgl,fSigned1Pt
0,0,1,1,0.034665,-3.093559,0.027728,0.352128,7.131713e-07,0.086724,-2.122640
1,0,1,1,-0.038039,1.057922,0.028758,0.347082,-5.348148e-07,0.565963,1.860431
2,0,1,1,0.004959,-1.053308,-0.046906,0.348381,-3.636550e-06,0.053010,3.211388
3,0,1,1,-0.037739,1.075205,0.016507,0.352450,2.594715e-08,-0.032695,-1.130452
4,0,1,1,0.040489,-2.265095,-0.006677,0.362991,9.847126e-07,-0.628449,-2.689926
...,...,...,...,...,...,...,...,...,...,...
66821,12541,1,1,0.001614,2.176665,-0.170785,0.111903,2.910637e-06,0.714509,-1.140240
66822,12542,1,1,-0.017821,-0.633107,-0.050015,0.588715,1.021886e-06,0.804855,-1.867598
66823,12542,1,1,0.022968,-1.463877,-0.052201,0.591380,6.491810e-07,0.671859,-1.994020
66824,12543,1,1,-0.023210,-0.312354,-0.026541,-1.899057,-1.161476e-07,0.288048,0.931763
66825,12544,1,1,-0.034925,0.152008,-0.022395,-0.069220,6.982006e-07,-0.235894,-2.004893

In [115]:
extra = file["/".join([example,extra_ID])].arrays(library="pd")
extra

,fPt,fEta,fCharge,fDcaXY,fDcaZ,fSigmaDcaXY2,fSigmaDcaZ2,fNsigmaTPCpi,fNsigmaTPCka,fNsigmaTPCpr,fNsigmaTOFpi,fNsigmaTOFka,fNsigmaTOFpr
0,0.471111,0.086615,-1,0.004583,-0.002375,0.000025,0.000025,1.296971,-6.567831,-14.216860,5.796030,-34.445034,-77.350662
1,0.537510,0.539420,1,0.011716,-0.007421,0.000023,0.000027,9.544146,1.979263,-9.118285,47.058315,2.731402,-34.971691
2,0.311392,0.052986,1,-0.005521,-0.006123,0.000064,0.000071,-1.248399,-12.175531,-12.922401,-999.000000,-999.000000,-999.000000
3,0.884602,-0.032689,-1,-0.001190,-0.002054,0.000013,0.000014,0.343225,-1.040863,-6.603751,-999.000000,-999.000000,-999.000000
4,0.371757,-0.593066,-1,0.003221,0.008487,0.000050,0.000071,-1.047941,-8.668435,-15.893881,-999.000000,-999.000000,-999.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66821,0.877008,0.664512,-1,-0.216790,0.042934,0.000041,0.000061,6.257855,5.419341,-0.965007,-999.000000,-999.000000,-999.000000
66822,0.535447,0.736455,-1,-0.002640,-0.001176,0.000055,0.000093,3.456773,-1.037680,-9.134036,17.396927,-0.634174,-27.424397
66823,0.501500,0.629460,-1,-0.007096,0.001489,0.000037,0.000059,41.929096,20.745060,0.401821,-999.000000,-999.000000,-999.000000
66824,1.073234,0.284206,1,0.003753,-0.000352,0.000015,0.000020,-0.064112,-0.084834,-4.473876,1.251596,-7.594126,-23.805223
66825,0.498780,-0.233759,-1,-0.001811,-0.002435,0.000026,0.000028,0.681258,-5.687005,-13.564117,6.591163,-29.214376,-66.758224

In [119]:
names = file.classnames(filter_classname="TDirectory")
bucket = []

# merge all files and keep:
# - |fPosZ| < 10 cm
# - |eta| < 0.8

max_pos_Z = 10
max_eta = 0.8

for item in names:
    candidate_ID = item
    collision = file[("/".join([candidate_ID,collision_ID]))].arrays(["fPosZ"],library="pd")
    track = file[("/".join([candidate_ID,track_ID]))].arrays(["fIndexCollisions", "fAlpha"],library="pd")
    extra = file[("/".join([candidate_ID,extra_ID]))].arrays(["fPt", "fEta", "fCharge", "fDcaXY", "fNsigmaTPCpi", "fNsigmaTPCka",
                                                              "fNsigmaTOFpi", "fNsigmaTOFka"],library="pd")
    complete = ( extra.merge(track, left_index = True, right_index = True) ).merge(collision, left_on ="fIndexCollisions", right_index = True )
    complete = complete[ (np.abs(complete["fPosZ"]) < max_pos_Z ) & ( np.abs(complete["fEta"]) < max_eta ) ]
    complete["file_ID"] = candidate_ID
    bucket.append(complete)
                                                                          
base = pd.concat(bucket, ignore_index=True)

In [120]:
base

,fPt,fEta,fCharge,fDcaXY,fNsigmaTPCpi,fNsigmaTPCka,fNsigmaTOFpi,fNsigmaTOFka,fIndexCollisions,fAlpha,fPosZ,file_ID
0,0.471111,0.086615,-1,0.004583,1.296971,-6.567831,5.796030,-34.445034,0,-3.093559,0.354504,DF_2298181510431936;1
1,0.537510,0.539420,1,0.011716,9.544146,1.979263,47.058315,2.731402,0,1.057922,0.354504,DF_2298181510431936;1
2,0.311392,0.052986,1,-0.005521,-1.248399,-12.175531,-999.000000,-999.000000,0,-1.053308,0.354504,DF_2298181510431936;1
3,0.884602,-0.032689,-1,-0.001190,0.343225,-1.040863,-999.000000,-999.000000,0,1.075205,0.354504,DF_2298181510431936;1
4,0.371757,-0.593066,-1,0.003221,-1.047941,-8.668435,-999.000000,-999.000000,0,-2.265095,0.354504,DF_2298181510431936;1
...,...,...,...,...,...,...,...,...,...,...,...,...
28804204,0.365911,0.692977,1,-0.002783,-1.105304,-8.723518,-999.000000,-999.000000,8985,-2.204511,-1.363117,DF_2298181516206624;1
28804205,0.307151,0.139667,-1,0.005647,-1.622144,-13.117761,-999.000000,-999.000000,8985,1.926254,-1.363117,DF_2298181516206624;1
28804206,0.844474,-0.153770,1,-0.003870,12.799761,9.454988,-999.000000,-999.000000,8985,1.015734,-1.363117,DF_2298181516206624;1
28804207,0.648469,0.311431,-1,-0.002017,-1.581579,-4.592941,-999.000000,-999.000000,8986,-0.396717,-1.062187,DF_2298181516206624;1
28804208,0.483286,-0.334097,-1,0.006152,0.553418,-6.092318,-999.000000,-999.000000,8986,1.671716,-1.062187,DF_2298181516206624;1